### PR TITLE
Musician

### PR DESCRIPTION
**Pull request by TybaIt**
First beta of the Musician module.

- Support of all instruments to preview melodies and emulate keys.
- Synthesia practice mode still WIP.
- Composer is still WIP.

Some XML files (melodies) for testing can be downloaded [here](https://anonfile.com/TecdG6s0n9/musician_zip).
extract to `..\Documents\Guild Wars 2\addons\blishhud\musician\*.xml`

**Dependencies**
[NAudio](https://github.com/naudio/NAudio) ([On NuGet](https://www.nuget.org/packages/NAudio/))
[NAudio.Vorbis](https://github.com/NAudio/Vorbis/) ([On NuGet](https://www.nuget.org/packages/NAudio.Vorbis/))

### CODE REVIEW

**Comment by dlamkins** [comment]
This looks really good!  I'll take a closer look tonight.  :)

**Comment by TybaIt** [comment]
Things that I put outside of module folder for general use (I will use some of these for SpecialForcesTraining as well.)
- Controls\Intern\*
- Controls\Extern\*
- Controls\HealthPoolButton.cs
- Controls\CounterBox.cs -- I will at a bool IsVendorStyle (or (IsSettingsStyle) to this as you said you wanted that in vendor style.
- Interfaces\IKeyboard.cs
- _Extensions\TimeSpanExtension.cs

I made this pull request because the module is big and wanted to have some testings and feedbacks. But especially because I edited the ContentService and don't want conflicts later on.

**Comment by dlamkins** [comment]
I just realized that because they aren't included directly in the project, the check AppVeyor does won't catch any problems.  I think future PRs will want to have all of the stuff added in to allow that check to complete with the new code.

**Comment by dlamkins** [comment]
Also looks like some of the images for the music conveyor belt didn't get moved over into ref.  Could you check for those and do a PR for those?

**Pull request merged**
